<a href="https://colab.research.google.com/github/haox2/PytorchTut/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.



In [3]:
import torch
import numpy as np

# **LISTS**


In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.90520278, 0.49315198, 0.93821157, 0.47196414],
       [0.36175929, 0.95380347, 0.23696783, 0.91694017],
       [0.13174574, 0.4646365 , 0.38753312, 0.20720666]])

In [6]:
np1.dtype


dtype('float64')

# **TENSORS**

In [14]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.4955,  0.6672, -1.2533,  0.2112],
        [-1.3676,  0.1025, -0.7696, -0.7377],
        [ 0.1041,  1.4991,  0.7756,  1.1182]])

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9052, 0.4932, 0.9382, 0.4720],
        [0.3618, 0.9538, 0.2370, 0.9169],
        [0.1317, 0.4646, 0.3875, 0.2072]], dtype=torch.float64)