<a href="https://colab.research.google.com/github/haox2/PytorchTut/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import torch

In [26]:
my_torch = torch.arange(12)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
# Reshape and View
my_torch = my_torch.reshape(3,4)
my_torch

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [28]:
# Reshape if we dont know the number of items using -1
# reshape(2, -1), 2 by something. 10 can be 2 by 5.-1 helps to find that number
my_torch_2 = torch.arange(10)
my_torch_2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch_2 = my_torch_2.reshape(2,-1)
my_torch_2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
my_torch_3 = torch.arange(10)
my_torch_3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_torch_4 = my_torch_3.view(2,5)
my_torch_4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Differences between reshape and view
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [33]:
# with reshape and view, they will update
my_torch_5 = torch.arange(10)
my_torch_5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
my_torch_6 = my_torch_5.reshape(2,5)
my_torch_6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [35]:
my_torch_5[1] = 4141
my_torch_5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [36]:
my_torch_6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [37]:
# Slices
my_torch_7 = torch.arange(10)
my_torch_7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# Grab a specific item
my_torch_7[7]

tensor(7)

In [41]:
# Grab slice
my_torch_8 = my_torch_7.reshape(5,2)
my_torch_8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [42]:
my_torch_8[:,1]

tensor([1, 3, 5, 7, 9])

In [44]:
# Return column
my_torch_8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])